on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregistry1999.azurecr.io
        username: ${{ secrets.acr_containerregistry1999_username }}
        password: ${{ secrets.acr_containerregistry1999_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t containerregistry1999.azurecr.io/edgecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push containerregistry1999.azurecr.io/edgecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_edgecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep edgecluster8a73 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace edgecluster8a73`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: edgecluster8a73
        container-registry-url: containerregistry1999.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregistry1999_username }}
        container-registry-password: ${{ secrets.acr_containerregistry1999_password }}
        secret-name: edgeclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: edgecluster8a73
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          containerregistry1999.azurecr.io/edgecluster:${{ github.sha }}
        imagepullsecrets: |
          edgeclusterdockerauth
